Correct --DatabasePassword command
The command was missing a 'd'. Running the current command gives:

Error: Invalid option(s):
--DatabasePasswor
   '--DatabasePasswor' is not a valid option