Security config prefix change
Without the slash being added before 'media', I get the following error in the logs when image are trying to be served,
"ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 610 : No image exists at ..."

The images are still served but adding the slash at the beginning removes the error.