Code snippets does not get syntax highlighting.
This page code does not get syntax highlighting with the ```cs, which also create uncompiling code in the ExamineComposer section, since the type paramter is not rendered on Our.Umbraco.

The code in the docs on Our does not combile, since ComponentComposer requires 1 type argument. 
Currently if you code and paste the ExamineComposer on this page (https://our.umbraco.com/documentation/Reference/Searching/Examine/examine-events) into your code, you will get these two error: 
- Using the generic type 'ComponentComposer<TComponent>' requires 1 type arguments
- 'ExamineComposer' does not implement interface member 'IComposer.Compose(Composition)'

However by using ```c# like all the other pages, we should both get syntax highlighting and hopefully also the missing type paramter.