Fixes issue
Fixes...

The name 'RuntimeLevel' does not exist in the current context (Compiler Error CS0103)

... in line...

[RuntimeLevel(MinLevel = RuntimeLevel.Run)]

... when using Umbraco version 8.6.3.